### ISSUE TITLE
Show type information in jsdoc

### ISSUE THREAD

**Issue by lars-vc** [Fildo7525/pretty_hover#10]
Currently, in jsdoc the type information is hidden, I think this is very valuable to be shown in the popup.
My proposal would be right after the variable with `: type`, so e.g. `information_source: string`
![image](https://user-images.githubusercontent.com/57136208/232542057-132b835b-0066-4d1e-a300-6b2a740bb99e.png)

**Comment by Fildo7525** [comment]
Well, this plugin just parses the doxygen information that is passed by the hover functionality. If you do the classical hover
```vim.lsp.buf.hover()``` the text that is displayed is passed for parsing. Therefore, this is a language-specific functionality.
