### ISSUE TITLE
Integration with completion plugins

### ISSUE THREAD

**Issue by proatgram** [Fildo7525/pretty_hover#11]
Currently this plugin requires a call to `require("pretty_hover").hover()` in order to trigger the hover, however, some other plugins, for example nvim-cmp, an advanced completion plugin, automatically triggers the LSP popups in Neovim without the need to call or hit a keybind to bring it up. Would it be possible to integrate a way to use this in plugins similar to those?

I did some research on nvim-cmp last night and it looks like there's a function you can set to format lines being displayed by nvim-cmp (see [this](https://github.com/hrsh7th/nvim-cmp/blob/2743dd989e9b932e1b4813a4927d7b84272a14e2/doc/cmp.txt#L518C19-L518C19)) and there's a function in `pretty_hover.utils` that converts text to Markdown. so I was thinking I could integrate the two, but I haven't had a chance to look into it further.

**Comment by proatgram** [comment]
I've had a bit more time to look into it a bit more and I think that `formatting.format` function in nvim-cmp might only be to format the completion menu, and not the documentation menu.

**Comment by Fildo7525** [comment]
Maybe calling the function every time this auto command is triggered could be the answer.
CursorHold			When the user doesn't press a key for the time
				specified with ['updatetime'](https://neovim.io/doc/user/options.html#'updatetime').

**Comment by Fildo7525** [comment]
Well, the auto command was not the right way. I looked at the cmp interface and how I implemented it so I could check some functionality and the documentation text formatting is not enabled in the nvim-cmp API. Therefore, this is not possible yet, but if the API gets extended, I will look into that.
