### ISSUE TITLE
feature to toggle hover

### ISSUE THREAD

**Issue by vishal340** [Fildo7525/pretty_hover#12]
is it possible to add require("pretty_hover").toggle()

**Comment by Fildo7525** [comment]
Hi, what would you like to do with the toggle? You can assign the ```require"pretty_hover".hover()``` function as ft plugin and you do not need a toggle.

**Comment by vishal340** [comment]
the same key should be able to open and close the hover. but i think it might be impossible because pressing the key again shifts you inside the hover

**Comment by Fildo7525** [comment]
it is just a question of one bool in the config of the hover callback. Would you like to have a different function like the "toggle" you mentioned or have it in config to set it up for the default "hover" function?

**Comment by Fildo7525** [comment]
@vishal340 try bran [feature-#12](https://github.com/Fildo7525/pretty_hover/tree/feature-%2312) if it aligns with what you want.

**Comment by Fildo7525** [comment]
I am merging the created chages
