### ISSUE TITLE
Misaligned code sections

### ISSUE THREAD

**Issue by Blackdeer1524** [Fildo7525/pretty_hover#13]
**Describe the bug**
Indentation is missing in code section. 

**To Reproduce**
You can see this effect when code section is sufficiently long
1. Create some cpp file 
2. paste this code
```cpp
#include <memory>

class SomewhatLongClassName {
 public:
    SomewhatLongClassName() = default;
    SomewhatLongClassName(SomewhatLongClassName &&a) = default;
};

auto main(int argc, char *argv[]) -> int {
    auto bar = SomewhatLongClassName{};
    auto f = std::make_shared<SomewhatLongClassName>(std::move(bar));
}
```
3. Hover on `make_shared`
4. See missing indentation

**Expected behavior**
Expected to see indentation in code section

**Screenshots**
pretty_hover:
![Screenshot from 2024-04-11 17-57-58](https://github.com/Fildo7525/pretty_hover/assets/52544736/bf2a4a5d-601b-4c11-a169-7af9fd972132)

native hover:
![Screenshot from 2024-04-11 17-57-50](https://github.com/Fildo7525/pretty_hover/assets/52544736/3fccb4fd-db00-4826-8110-712df6111e6d)

**Desktop (please complete the following information):**
 - Nvim version: NVIM v0.10.0-dev-2267+g6709f7f8f 
 - OS: Linux; Pop!_OS 22.04 LTS
 - LSP from example: clangd 17.0.3

**Additional context**
Missing indentation makes particularly long code sections unreadable.
pretty_hover:
![Screenshot from 2024-04-11 18-00-16](https://github.com/Fildo7525/pretty_hover/assets/52544736/b0e23eff-5f5b-4ea1-ac8d-98db1cd187bc)

native hover:
![Screenshot from 2024-04-11 18-00-37](https://github.com/Fildo7525/pretty_hover/assets/52544736/dad627fe-7f5c-416f-a44a-0491d5c38be5)

**Comment by Fildo7525** [comment]
Hi could you switch to branch issue-#13 and check if it works for you? Thanks.

**Comment by Blackdeer1524** [comment]
It does, thanks
