### ISSUE TITLE
(Golang) No indentation in code sections

### ISSUE THREAD

**Issue by Blackdeer1524** [Fildo7525/pretty_hover#17]
**Describe the bug**
Indentation is missing in code section. Related to #13 

**To Reproduce**
Hover on struct on struct or interface declaration. 
Code example:
```go
package main

type Foo struct {
	foo int
	bar int
}

type Some interface {
	Foo()
}
```

**Expected behavior**
Expected to see indentation in code section

**Screenshots**
pretty_hover:
- struct fields
![image](https://github.com/Fildo7525/pretty_hover/assets/52544736/111ea8f7-1899-4dbf-a6fc-c878e7f6eb00)
- interface
![image](https://github.com/Fildo7525/pretty_hover/assets/52544736/cf18b5ff-1ede-4e44-998b-7e1bb35dd2fd)

native hover:
- struct fields
![image](https://github.com/Fildo7525/pretty_hover/assets/52544736/32b3480b-c728-4cf9-a7df-d2c667a1b516)
- interface
![image](https://github.com/Fildo7525/pretty_hover/assets/52544736/e602e329-5d8f-4636-85ed-84d93cc12b92)

Desktop:
- Nvim version: NVIM v0.10.0-dev-2267+g6709f7f8f
- OS: Linux; Pop!_OS 22.04 LTS
- LSP from example: gopls v0.15.2

**Comment by Blackdeer1524** [comment]
Problem also showes up in "Embedded fields" section:

native hover:
![image](https://github.com/Fildo7525/pretty_hover/assets/52544736/f854f12a-008b-4753-9da1-0aa4ace3bff5)

pretty_hover:
![image](https://github.com/Fildo7525/pretty_hover/assets/52544736/3c5155a5-7590-4f22-94b5-11266b831108)

Code:
```go
package main

import "text/template"

func main() {
	f := map[string]*template.Template{}
	f["a"] = nil
}
```

**Comment by Fildo7525** [comment]
Hi, I have pushed the changes now is should be partially ok. I still need to preserve the inline whitespace. However, the indentation is fixed.

**Comment by Fildo7525** [comment]
That was faster than I expected. Can you confirm that it works?
