### ISSUE TITLE
Trying to index nil value.

### ISSUE THREAD

**Issue by BigCrow** [Fildo7525/pretty_hover#19]
**Describe the bug**
Activating hover on some symbols would try to access a value that doesn't exist & triggers an error.

It is due to line 13 in lua/pretty_hover/init.lua:
```lua
	hover_text = contents[1].value
```

add a pcall test to fix this. Here an example fix:
```lua
    -- Add a test in case there are no contents.
    if not pcall(function()
        hover_text = contents[1].value
    end) then
        return
    end
```

**Comment by Fildo7525** [comment]
Thank you for the fix. I just pushed it to the master branch
