### ISSUE TITLE
Error in Java

### ISSUE THREAD

**Issue by Abh15h3k** [Fildo7525/pretty_hover#2]
In some cases `require"pretty_hover".hover()` for java fails with the following error.

![Screenshot 2023-04-10 at 12 08 10 AM](https://user-images.githubusercontent.com/40197742/230790675-e05a0779-4752-47f6-9c21-9c1fa05ddfb6.png)

I did some debugging myself...
Looks like the issue is that the `contents` in the response isn't always a simple table.

For example...

when i run hover on the `main` function of java it is...
![Screenshot 2023-04-10 at 12 05 56 AM](https://user-images.githubusercontent.com/40197742/230790861-feb1d6bd-39c5-425f-b2f4-e8a68ccc07a7.png)

But when i run hover on the `run` method of SpringApplication class. it is...
![Screenshot 2023-04-10 at 12 06 52 AM](https://user-images.githubusercontent.com/40197742/230790968-57f965b9-6f2c-44a0-a9ca-47a4dac3bfad.png)

This is the solution i came up with. let me know if this makes sense. i can raise a PR
```
vim.lsp.buf_request_all(0, 'textDocument/hover', params, function(responses)
    for _, response in pairs(responses) do
        if response.result and response.result.contents then

            local contents = response.result.contents

            if type(contents) == "table" then
                for _, content in pairs(contents) do
                    local hover_text = content.value or content
                    -- Convert Doxygen comments to Markdown format
                    local tbl = h_util.convert_to_markdown(hover_text, M.config)

                    local bufnr, winnr = vim.lsp.util.open_floating_preview(tbl, 'markdown', {border = M.config.border, focusable = true})
                    M.bufnr = bufnr
                    M.winnr = winnr

                    vim.keymap.set('n', 'q', function ()
                        api.nvim_win_close(winnr, true)
                        M.winnr = 0
                        M.bufnr = 0
                    end, { buffer = bufnr, silent = true, nowait = true })
                end
            else
                local hover_text = response.result.contents.value
                -- Convert Doxygen comments to Markdown format
                local tbl = h_util.convert_to_markdown(hover_text, M.config)

                local bufnr, winnr = vim.lsp.util.open_floating_preview(tbl, 'markdown', {border = M.config.border, focusable = true})
                M.bufnr = bufnr
                M.winnr = winnr

                vim.keymap.set('n', 'q', function ()
                    api.nvim_win_close(winnr, true)
                    M.winnr = 0
                    M.bufnr = 0
                end, { buffer = bufnr, silent = true, nowait = true })
            end
        end
    end
end)

```

PS.

my understanding of the inner workings of neovim is basic.
so my solution is probably wrong (my concern is that `open_floating_preview` is getting called for every entry in `contents`. which gives me the feeling that multiple floating windows will open....

**Comment by Fildo7525** [comment]
I have checked the code It makes sense. I have refactored it a bit. The issue#1 reappears again after this change. I will try to fix it. You can temporarily checkout [this](https://github.com/Fildo7525/pretty_hover/tree/issue%232) branch. It has the fix in it. Later this will be merged to master.

**Comment by Abh15h3k** [comment]
> EDIT: Increasing the PR would be great. Thanks.

not sure what you mean.
Do you mean i should make a PR?

**Comment by Fildo7525** [comment]
No you mentioned befor I think it was misunderstanding

**Comment by Fildo7525** [comment]
Ok try it now. It should work

**Comment by Abh15h3k** [comment]
> No you mentioned befor I think it was misunderstanding

Sorry. getting confused. what did i mention?
what should work now?

**Comment by Fildo7525** [comment]
> This is the solution I came up with. let me know if this makes sense. I can raise a PR

Does not matter. If you pull the changes do they work or not? I did not find anything that would raise an error like this.

**Comment by Abh15h3k** [comment]
ok.

switching to the issue#2 branch fixes my issue

**Comment by Abh15h3k** [comment]
> > This is the solution I came up with. let me know if this makes sense. I can raise a PR
> 
> Does not matter. If you pull the changes do they work or not? I did not find anything that would raise an error like this.

I just created a sprint starter from start.spring.io

**Comment by Fildo7525** [comment]
Now I am not catching up

**Comment by Abh15h3k** [comment]
if you want to try and reproduce the issue. so that you have the exact source i do...

I just went to start.spring.io

**Comment by Abh15h3k** [comment]
also this might matter.

i'm using neovim nightly.
my current version:

```
:version
NVIM v0.10.0-dev-17+g6801befcc5
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -W
shadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-c
ommon -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DI
NCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/usr/include/luajit-2.1 -I/usr/include -I/usr/include -I/home/abhishek/.
cache/paru/clone/neovim-git/src/build/src/nvim/auto -I/home/abhishek/.cache/paru/clone/neovim-git/src/build/include -I
/home/abhishek/.cache/paru/clone/neovim-git/src/build/cmake.config -I/home/abhishek/.cache/paru/clone/neovim-git/src/n
eovim/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include
```

**Comment by Fildo7525** [comment]
Ok I did know about that page. Thanks. Well that may have something with it. I did it no the appimage on 0.9.0

**Comment by Fildo7525** [comment]
I have merged it to master and I am going to delete the branch so that you know.
