### ISSUE TITLE
Get_active_clients is not called on nvim v0.9.5

### ISSUE THREAD

**Issue by BigCrow** [Fildo7525/pretty_hover#20]
**Describe the bug**
In [#3e5bb78 ](https://github.com/Fildo7525/pretty_hover/commit/3e5bb78334a69190d90d52aa022a7e00e25ef2b8) a check is added to test nvim version ``vim.fn.has("nvim-0.11.0")``. However this check always returns a value (I think it is either 0 or 1).
On nvim v0.9.5 it retuns 0.

Current line in lua/pretty_hover/util.lua:70
```lua
	if vim.fn.has("nvim-0.11.0") then
```

It should be changed to
```lua
	if vim.fn.has("nvim-0.11.0") ~= 0 then
```

**Comment by Fildo7525** [comment]
Actually, that did not work either. I chose the vim.version().minor check. This one I checked across 3 versions.

**Comment by Fildo7525** [comment]
Can you confirm that it works?

**Comment by BigCrow** [comment]
This works :+1:
