### ISSUE TITLE
Pretty hover fails with relay_lsp

### ISSUE THREAD

**Issue by Jomik** [Fildo7525/pretty_hover#23]
**Describe the bug**
Pretty hover fails with `relay_lsp` on schema fields.

**Expected behavior**
![image](https://github.com/user-attachments/assets/d65c92f6-acc8-4628-aa6e-bb627b5a71ad)

**Screenshots**
![image](https://github.com/user-attachments/assets/96b64497-acde-47c8-9905-6a90f89d35f0)

**Comment by Fildo7525** [comment]
Hi, can you explain the issue a bit more? I tried to download it and it is not in the mason. Did you install it from source or is there any easier way of installing it (I am on ubuntu22)
