### ISSUE TITLE
One line of padding on both top and bottom of pretty hover

### ISSUE THREAD

**Issue by philocalyst** [Fildo7525/pretty_hover#24]
Hey! I find this plugin to make things more pretty! But I am running into a specific difficulty regarding that padding, as shown below. For very small definitions it can literally triple the size of the popup. If this is a stylistic choice, could an option be added to turn it off?

<img width="517" alt="image" src="https://github.com/user-attachments/assets/aab923b7-b894-4f26-b43a-3e2dc44963d4">

**Comment by iguanacucumber** [comment]
It's because under the hood it's just hidden markdown 
![image](https://github.com/user-attachments/assets/39241fc1-4198-4184-b7f1-9e8f5abcba4f)

**Comment by iguanacucumber** [comment]
( i forgot to say that vanilla neovim works like that, and it's noice.nvim which removes the padding by removing the markdown text )

**Comment by philocalyst** [comment]
I suspected this but didn't understand the need -- in the term it's all just plaintext, modified by colors and font-options, so wouldn't it be easy enough to just convert the source markdown into text with the equivalent formatting?  I could help!

**Comment by iguanacucumber** [comment]
there's alot of `return ""` inside this plugin this might the culprit

**Comment by iguanacucumber** [comment]
i'm not a lua dev but the issue seems to be in either util.lua or references.lua

**Comment by Fildo7525** [comment]
Hi, to clarify. Would you like to remove it just from the one-line statements? If yes and you do not care about the highlighting it would be easier (i.e. the number color)

**Comment by iguanacucumber** [comment]
Hi, i just want to remove the "padding" above and below "22 bytes"
I don't really care about the highlighting

**Comment by Fildo7525** [comment]
Hi, can you confirm that it works also for your usecase?

**Comment by iguanacucumber** [comment]
works perfectly
