### ISSUE TITLE
[Request] Expose float close function

### ISSUE THREAD

**Issue by miversen33** [Fildo7525/pretty_hover#6]
First, fantastic plugin! I currently use `hover.nvim` (the inspiration for this), however I am not against switching to something I have more control over :)

That said, IMO the [float close functionality](https://github.com/Fildo7525/pretty_hover/blob/6cefe0c0d6a0435a545f86613da7b2adb70bb957/lua/pretty_hover/util.lua#L118-L122) should be exposed (something like `require("hover").close()`?)

My use case here would be that if I press `ESC`, I would want the hover window to close even if I am not currently in it (I don't usually shift my cursor focus to the documentation window)

Thoughts on something like that? I would be willing to submit a PR for it if you are open to it :)

**Comment by Fildo7525** [comment]
Yea sure why not. If you have a use case for it, I think you will not be alone.

**Comment by Fildo7525** [comment]
It is a small change so I can make it as a next commit or you can create a PR.
