### ISSUE TITLE
[Bug] Error when no hover available

### ISSUE THREAD

**Issue by Jomik** [Fildo7525/pretty_hover#8]
![image](https://user-images.githubusercontent.com/699655/231154573-8d441c26-eec9-4b21-9f9c-965d796768b0.png)
I get this error when no lsp hover is available.

**Comment by Fildo7525** [comment]
Could you specify a bit more? like what file type did you use? I do not want to just do a fix if `toSplit` is `nil`. I just want to investigate it a bit more so that this error will not appear in more cases with a bit different variation.

**Comment by Jomik** [comment]
Weird!
I created a more minimal repro, can you try to see if this works for you?
https://gist.github.com/Jomik/1fa4569d2fbe95f5d338019d5859af1a
You should be able to run it by running `nvim -u repro.lua` and let it install everything (most of LazyVim...) and then `nvim -u repro.lua config.schema.json`, wait for it to install the LSP and such.
Run `:Lazy` to ensure that `pretty_hover` loaded, or restart nvim and open the file again..
That at least consistently gives me the above error, and is less bloated than my personal setup.
All the plugins are stored in a `.repro` folder.

**Comment by Fildo7525** [comment]
I have just pushed a fix for the issue that I had. Try fetching the changes if it fixed yours too.

**Comment by Fildo7525** [comment]
You can create a new feature request. So it would be separated from this issue.
